- Somme matricielle et boradcasting

# NUMPY BROADCASTIN

__Attention : ca peut etre dangereux__

[video 13](https://www.youtube.com/watch?v=RwFiNlL4Q8g)

Permet de faire des calcul entre un tableau A et un tableau B de facon tres rapide.

- En C, on devrait faire des boucles for, cellules par cellules
- Avec numpy, il suffit d'ecrire A + B (__il faut que les tableaux aient les memes dimension = ce sont des matrices)

In [4]:
import numpy as np

np.random.seed(0)
A = np.random.randint(0, 10, (2, 3))
B = np.ones((2, 3))
A + B 

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

Pour faire des calcules entre tableaux qui n'ont pas la meme dimension, on peut etre certaines dimensions que n'auraient pas nos tableaux

= BROADCASTING

(qui se fait automatiquement en sommant une matrice a un scalaire)

In [5]:
B = np.ones((2,1))
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

Ca marche aussi avec un vecteur, car les colonnes de C ont ete etendues pour couvrir la taille du tableau A

In [6]:
B = np.ones((4,1))
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (4,1) 

__Ne fonctionne pas si le nombre de colonne ne correspond pas entre nos deux matrices__

A et B doivent avoir le meme nombre de dimensions (mm nb lignes et mm nb colonne, ideal), ou une dimension respective egale a 1 (une mm dimension)

Fonctionne aussi pour deux vecteurs :

In [8]:
A = np.ones((4,1))
B = np.ones((1,3)) # Attention c'est le meme resultats que quand B.shape() = (3,)
A+B
# quand on travaille avec des matrices a dimensions incompletes, on pourrait avoir des operations de broadcasting completement inentionnonee

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

__Toujours verifier les dimensions de nos tableaux et utiliser la fonction reshape pour eviter les broadcastings involontaires. Ca pourrait fausser tous nos resultats__

# Synthese Numpy

- Constructeurs : nparray, 0s, 1s rands
- Manipulations : A.reshape(shape), np.concatenate((A,B), axis=0), concatenate() // reshape quand les dimensions sont incompletes
- Maths : max(), min(), mean(), argmin(), argmax(), __argsort()__
- Boolean indexing
- Boradcasting

__Preferer scipy pour l'utilisation de fonctions mathematiques avancees__