- sum(), cumsum(), cumprod(), min(), max(), argmin(), argmax()
- argsort()
- corrcoef()
- NaN corrections
- algebre lineaire
- standardiser une matrice

# NUMPY STATS & MATHS

[video 12](https://www.youtube.com/watch?v=RwFiNlL4Q8g)

[methodes de ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html)

- sum() : Les sommes sur les axes "sum(axis = x)" seront determinantes
- sort()
- max()
- min()
- mean()

__argmin()__ & __argmax()__ pour trouver nos __index de min() et de max()__

In [34]:
import numpy as np

A = np.random.randint(0, 10, (5, 5))
print(A)
print(A.sum())
print("Somme ligne 1 : ", A[0].sum())
print("Asum(axis = 0) : ",A.sum(axis=0)) # retourne une ligne avec la somme de chaque colonne comme cellule (array)
print("Somme ligne 2 : ", A[1].sum())
print("sum(axis = 1) : ",A.sum(axis=1)) # retourne une colonne avec la somme de chaque ligne comme cellule (array)
print("Somme cumulee : ",A.cumsum())
print("Somme cumulee, axe 0 : \n",A.cumsum(axis=0))
print("Somme cumulee, axe 1 : \n",A.cumsum(axis=1)) 
#cumprod() fait le produit cumulee, comme cumsum la somme
print("minimum axe 0 : \n",A.min(axis=0)) 
print("minimum axe 1 : \n",A.min(axis=1)) 
# Pour trouver la position du minimum
print("Index du minimum axe 0 : \n",A.argmin(axis=0)) 
print("Index du minimum axe 1 : \n",A.argmin(axis=1)) 
# Si le nombre apparait deux fois, c'est le premier index qui est retournee

[[6 0 6 1 2]
 [7 0 2 0 2]
 [4 4 9 8 8]
 [8 2 9 6 9]
 [4 4 0 0 5]]
106
Somme ligne 1 :  15
Asum(axis = 0) :  [29 10 26 15 26]
Somme ligne 2 :  11
sum(axis = 1) :  [15 11 33 34 13]
Somme cumulee :  [  6   6  12  13  15  22  22  24  24  26  30  34  43  51  59  67  69  78
  84  93  97 101 101 101 106]
Somme cumulee, axe 0 : 
 [[ 6  0  6  1  2]
 [13  0  8  1  4]
 [17  4 17  9 12]
 [25  6 26 15 21]
 [29 10 26 15 26]]
Somme cumulee, axe 1 : 
 [[ 6  6 12 13 15]
 [ 7  7  9  9 11]
 [ 4  8 17 25 33]
 [ 8 10 19 25 34]
 [ 4  8  8  8 13]]
minimum axe 0 : 
 [4 0 0 0 2]
minimum axe 1 : 
 [0 0 4 2 0]
Index du minimum axe 0 : 
 [2 0 4 1 0]
Index du minimum axe 1 : 
 [1 1 0 1 2]


## argsort

In [35]:
print("SUR UNE DIM")
srta = np.array([1,2,3,4])
print("argsort srta : \n",srta.argsort()) 
print()
print("SUR DEUX DIM")
print("A = \n", A)
print("argsort axe 0 : \n",A.argsort(axis=0)) 
print("argsort axe 1 : \n",A.argsort(axis=1)) 

# retourne des array

SUR UNE DIM
argsort srta : 
 [0 1 2 3]

SUR DEUX DIM
A = 
 [[6 0 6 1 2]
 [7 0 2 0 2]
 [4 4 9 8 8]
 [8 2 9 6 9]
 [4 4 0 0 5]]
argsort axe 0 : 
 [[2 0 4 1 0]
 [4 1 1 4 1]
 [0 3 0 0 4]
 [1 2 2 3 2]
 [3 4 3 2 3]]
argsort axe 1 : 
 [[1 3 4 0 2]
 [1 3 2 4 0]
 [0 1 3 4 2]
 [1 3 0 2 4]
 [2 3 0 1 4]]


[numpy routine math](https://numpy.org/doc/stable/reference/routines.math.html)

In [36]:
np.exp(A)

array([[4.03428793e+02, 1.00000000e+00, 4.03428793e+02, 2.71828183e+00,
        7.38905610e+00],
       [1.09663316e+03, 1.00000000e+00, 7.38905610e+00, 1.00000000e+00,
        7.38905610e+00],
       [5.45981500e+01, 5.45981500e+01, 8.10308393e+03, 2.98095799e+03,
        2.98095799e+03],
       [2.98095799e+03, 7.38905610e+00, 8.10308393e+03, 4.03428793e+02,
        8.10308393e+03],
       [5.45981500e+01, 5.45981500e+01, 1.00000000e+00, 1.00000000e+00,
        1.48413159e+02]])

# Statistiques np


In [37]:
A.mean(axis=0)

array([5.8, 2. , 5.2, 3. , 5.2])

In [38]:
# ecart type sur axe 0 
print(A.std(axis=0))
# ecart type sur axe 0
print(A.var(axis=0))

[1.6        1.78885438 3.65513338 3.34664011 2.92574777]
[ 2.56  3.2  13.36 11.2   8.56]


[numpy stats routines](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [39]:
print(A)
# corrcoeff : correlation entre les differentes lignes ou les differentes colonnes qu'on a dans notre tableau  ; ou meme entre n'importe quel tableau
np.corrcoef(A)

[[6 0 6 1 2]
 [7 0 2 0 2]
 [4 4 9 8 8]
 [8 2 9 6 9]
 [4 4 0 0 5]]


array([[ 1.        ,  0.77166375,  0.11010379,  0.71919495, -0.18350632],
       [ 0.77166375,  1.        , -0.3842598 ,  0.5090986 ,  0.34075869],
       [ 0.11010379, -0.3842598 ,  1.        ,  0.58421738, -0.59482759],
       [ 0.71919495,  0.5090986 ,  0.58421738,  1.        , -0.11965898],
       [-0.18350632,  0.34075869, -0.59482759, -0.11965898,  1.        ]])

Correlation de type

|| L1L1 || L1L2 ||

|| L2L1 || L2L2 ||

In [40]:
# COEEF CORRELATION L1L2
np.corrcoef(A)[0,1]

0.7716637473824918

In [43]:
print(A)

[[6 0 6 1 2]
 [7 0 2 0 2]
 [4 4 9 8 8]
 [8 2 9 6 9]
 [4 4 0 0 5]]


In [41]:
# Retrouver le nombre de repetitions d'un entite
print(np.unique(A, return_counts=True)) # retourne deux tableaux : les valeurs et leur compte


(array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([5, 1, 4, 4, 1, 3, 1, 3, 3]))


In [49]:
values, counts = np.unique(A, return_counts=True)

print("Count : ", counts)
# les differents index si on veut trier counts
print("La sequnce d'index pour trier count : ", counts.argsort())
# ces index, on va les injecter dans le tableau values pour avoir les nombres des moins presents aux plus presents
values[counts.argsort()]

Count :  [5 1 4 4 1 3 1 3 3]
La sequnce d'index pour trier count :  [1 4 6 5 7 8 2 3 0]


array([1, 5, 7, 6, 8, 9, 2, 4, 0])

In [50]:
for i,j in zip(values, counts) :
    print(f"Valeur {i} apparait {j} fois")

Valeur 0 apparait 5 fois
Valeur 1 apparait 1 fois
Valeur 2 apparait 4 fois
Valeur 4 apparait 4 fois
Valeur 5 apparait 1 fois
Valeur 6 apparait 3 fois
Valeur 7 apparait 1 fois
Valeur 8 apparait 3 fois
Valeur 9 apparait 3 fois


In [51]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]) :
    print(f"Valeur {i} apparait {j} fois")

Valeur 1 apparait 1 fois
Valeur 5 apparait 1 fois
Valeur 7 apparait 1 fois
Valeur 6 apparait 3 fois
Valeur 8 apparait 3 fois
Valeur 9 apparait 3 fois
Valeur 2 apparait 4 fois
Valeur 4 apparait 4 fois
Valeur 0 apparait 5 fois


## NAN correction
__Not A Number__

In [52]:
A = np.random.randn(5, 5)
A[0,2] = np.nan
A[4, 3] = np.nan
A

array([[-2.05984089, -1.3819485 ,         nan,  1.05278168,  0.97484408],
       [-0.93831097, -0.85423699,  0.58698556, -1.31964681,  0.41339696],
       [ 0.11124807,  0.82941867, -0.21968378,  0.62027751, -0.273613  ],
       [-0.30074845, -1.05476417, -1.44708908,  0.35189007,  0.80095663],
       [-0.27932003,  0.90460093, -0.58279034,         nan,  0.19238938]])

In [53]:
A.mean()

nan

Toujours un peu filtrer, corriger notre datasset

Mais il existe des fonctions speciales pour effectuer les fonctions de base tout en ignorant les entites nan

- nanmean()
- nanstd()
- nanvar()

In [54]:
np.nanmean(A)

-0.168400150968888

In [57]:
np.isnan(A).sum()/A.size # estime la part de valeur nan, qui va donner la qualite du dataset

0.08

In [59]:
A[np.isnan(A)] = 0
np.isnan(A).sum()

0

# Algebre lineaire
[Calcul du determinant d'un matrice, wikipedia](https://fr.wikipedia.org/wiki/Calcul_du_d%C3%A9terminant_d%27une_matrice)

- la matrice doit etre carree
- permet de savoir si la matrice est inversible

__une matrice est inversible si et seulement si son déterminant est non nul__

[Mode math determinant et matrice](https://www.methodemaths.fr/determinant_matrice/)

Matrice 2x2 a,b ; c, d = ad - bc

Cas particulier
- matrice diagonale
- matrice triagulaire superieure et inferieure
On ne fait que multiplier les nombre de la diagonale


MATRICE INVERSIBLE 

En mathématiques et plus particulièrement en algèbre linéaire, une matrice inversible (ou régulière ou encore non singulière) est une matrice carrée A pour laquelle il existe une matrice B de même taille n avec laquelle les produits AB et BA sont égaux à la matrice identité.

    A B = B A = I n

In [60]:
# EXERCICE VIDEO
A = np.ones((2,3))
B = np.ones((3, 2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
# Transposer une matrice
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
# produit matriciel
print(A.dot(B))
print(B.dot(A))

[[3. 3.]
 [3. 3.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


[numpy algebre lineaire](https://numpy.org/doc/stable/reference/routines.linalg.html)

- Calculer un determinant
- inverser une matrice
- calculer les valeurs propres d'une matrice

In [69]:
A = np.random.randint(0, 10, (3,3))
np.linalg.det(A)

2.0000000000000027

In [70]:
np.linalg.inv(A)

array([[ 1.00000000e+00, -5.00000000e-01, -7.40148683e-17],
       [-2.50000000e+01,  1.70000000e+01, -2.00000000e+00],
       [ 1.10000000e+01, -7.50000000e+00,  1.00000000e+00]])

__p inverse, why ?__

In [71]:
np.linalg.pinv(A)

array([[ 1.00000000e+00, -5.00000000e-01, -1.68007412e-15],
       [-2.50000000e+01,  1.70000000e+01, -2.00000000e+00],
       [ 1.10000000e+01, -7.50000000e+00,  1.00000000e+00]])

Le principal component analysis utilise les valeurs propres (eigen values)

eigen vector = vecteur propre

In [72]:
np.linalg.eig(A)

(array([ 0.0537687 ,  3.15442407, 11.79180723]),
 array([[ 0.02595935, -0.49455239,  0.27487726],
        [-0.91367464, -0.67554364,  0.50313279],
        [ 0.40561652,  0.54686262,  0.81932893]]))

# Exercice
## Normaliser une matrice
Standardiser les differentes colonnes : mettre sur une meme echelle toutes les colonnes et lignes.

Plusieurs technique :
- rescaling (min-max) : (A - min(A))/(max(A)-min(A))
- mean normalization
- etc.

[Feature scaling](https://en.wikipedia.org/wiki/Feature_scaling)

Nous, c'est la standardization, c'est : 

(A - barreA)/signa(A)

avec barreA = averrage(A) et sigma(A) son ecart type

Faire cette operation de standardization sur chaque colonne du tableau. Comme si on avait un dataset ou la colonne 1 c'est le prix de differents appartements, et la colonne 2 c'est la surface. On va vouloir la moyenne des prix et la moyenne des surfaces, de meme pour l'ecart-type. Puis on pourra standardiser ces deux colonnes, independamment l'une de l'autre.

In [73]:
np.random.seed(0)
A = np.random.randint(0, 100, (10, 5))
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

### Standardization

In [77]:
ar_mean = np.mean(A, axis=0)
print(ar_mean)
ar_std = np.std(A, axis=0)
print(ar_std)
B = (A - ar_mean)/ar_std
B

[44.5 47.  60.5 45.7 64.5]
[22.66384786 22.28003591 26.5678377  29.36341261 23.2432786 ]


array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

- La moyenne de chaque colonne est egal a 0 (tend vers 0 pour etre precis)
- L'ecart-type de chaque colonne est egal a 1 

Chaque colonne soit une distribution normale quasiment parfaite

Correction : il le fait en une ligne, D = (A - A.mean(axis = 0))/A.std(axis = 0)