- Progammation orientee objet

# PROGRAMMATION ORIENTEE OBJET

[video 9](https://www.youtube.com/watch?v=2LdLiCtVUEA)

Un __objet__ a des __attributs__ qui le caracterisent et il peut realiser des __actions (methodes)__.

Noms, adjectifs, verbes

C'est dans une classe, qu'on definit les objets.

## La POO en machine learning
[numpy.ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

n dimensions array

tableau a n dimensions

__constructeur : la classe qui instancie l'objet__

In [2]:
import numpy as np

tableau = np.array([1,2,3])

In [3]:
print(tableau.size)

3


# NUMPY N-DIM / ML

[video 10](https://www.youtube.com/watch?v=NzDQTrqsxas)

Tableau numpy a 1 dimension equivalent a une liste, mais plus rapide et pratique pour les calculs mathematiques
Tableau numpy a 2 dimension ; les lignes sont les valeurs du dataset, et les colonnes, les variables et _features_



Dans un tableau a 2 dimensions on peut aussi stocker les pixels d'une image (valeur en noir et blanc).

Si on veut representer une image en couleur, alors on peut la decomposer en trois tableaux pour les valeurs de vert, bleu et rouge. (3D array)

## Attributs (extrait)
### ndarray.shape
[doc](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)
- _ndarray.shape_ : la forme du tableau (ligne, colonne, profondeur) = Tuple (immutable !)

Exemple : 
- si ndim = 1 pour 2 ligne, alors shape = (2)
- si ndim = 2 pour 2 lignes et 3 colonnes, alors shape = (2, 3)
- etc.

## Methodes
### Constructeurs

In [2]:
import numpy as np

tableau = np.array([1, 2, 3])
print(tableau.ndim)
print(tableau.shape)
print(tableau.size)

1
(3,)
3


In [8]:
# Initie un tableau de 2 lignes et trois colonne de 0 flottants
B = np.zeros(shape=(2,3), dtype=float)
B

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
B = np.ones(shape=(3,3), dtype=float)
B.size

9

In [12]:
B = np.full(shape=(3,3), fill_value=9)
B

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

[randn manual](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

Retourne des nombres aleatoires selon la distribution normale (Gaussienne) centree en 0

In [23]:
np.random.seed(0) #le nombre a l'interieur permet juste de fixer une distribution
# Genere de maniere aleatoire les nombres, sauf si "seede"
C = np.random.randn(3,4)
C

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [27]:
# Genere un tableau de nombre aleatoire sans distribution particuliere
test = np.random.random_sample((3,4))
test

array([[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918]])

In [30]:
# random integers
# Pour echantillonner avec N points, un espace compris entre a et b :
# a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)
-2.5 + (2.5 - (-2.5)) * (np.random.randint(10,size=10)-1) / (10-1.)

array([-2.5       ,  1.94444444,  1.94444444, -3.05555556, -0.83333333,
        0.83333333, -1.38888889, -1.94444444,  0.83333333, -1.94444444])

In [48]:
list_tst = ['michel', 'gilles', 'marta', 'fanta']

# Choisi deux elements de maniere aleatoire dans la liste
# replace = defini si l'element tire au hasard, reste un choix possible pour le tour suivant
np.random.choice(list_tst, size=2, replace=False)

array(['fanta', 'gilles'], dtype='<U6')

In [54]:
np.random.shuffle(list_tst)
list_tst

['gilles', 'marta', 'fanta', 'michel']

In [55]:
# Creer une matrice identite
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [70]:
D = np.array(np.arange(0, 10, 1), dtype=int)
print(D)
D = np.arange(0, 10, 1, dtype=int)
print(D)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [71]:
D = np.arange(0, 10, 0.5, dtype = np.float16)
print(D)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [72]:
D = np.arange(0, 10, 0.5, dtype = np.float64)
print(D)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


#### dtype

[dtype manual](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

La taille du type depend du compromis precision/rapidite du programme que l'on souhaite realiser

### Manipuler les tableaux numpy

In [103]:
A = np.zeros((3, 2))
B = np.ones((3,2))

#### Concatener : hstack (horizontal) & vstack(vertical)

In [104]:
C = np.hstack((A, B))
print(C.shape)
D = np.concatenate((A, B), axis=1)
print(D.shape)

(3, 4)
(3, 4)


In [105]:
C = np.vstack((A, B))
print(C.shape)
D = np.concatenate((A, B), axis=0)
print(D.shape)

(6, 2)
(6, 2)


#### Reshape (if size initial == size final)

In [106]:
print(D.size)
E = D.reshape((3,4)) # shape est un tuple
print(E.shape)
E

12
(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
A = np.array([1,2,3]) # retourn un tableau de shape (3,) 
# Mais cette commande retourne une erreur : print(A.shape[1])
# On veut donc rendre obvious qu'il y a une colonne pour eviter les bugs
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

In [108]:
# Parfois ce "1" obvious peut creer des problemes, notamment en visualisation de donnees
# Il est recommande pour le calcul matriciel, mais deconseille pour la visualisation de donnees
A = A.squeeze() # Fait disparaitre toutes les dimensions ou il y a simplement un 1
A.shape

(3,)

In [109]:
# Methode ravel permet d'applatir un table a ni dimension
print(D.shape)
D = D.ravel()
print("D.ravel()")
print(D.shape)

(6, 2)
D.ravel()
(12,)


# Exercice

In [129]:
def initialisation_mbr (m, n) :
    # m = nombre de lignes
    # n = nombre de colonnes
    # retourne une matrice aleatoire (m, n+1)
    # Avec une colonne 1 remplie de 1 tout a droite
    # Indice : il prefere la fonction randn()
    # randmat = np.random.random_sample(size=(m,n+1))
    randmat = np.random.randn(m,n+1)
    print(randmat)
    solomat = np.array([1 for i in range(m)], dtype = int)
    solomat = solomat.reshape((solomat.shape[0],1))
    print(solomat)
    # return np.concatenate((randmat,solomat), axis=0)
    return np.concatenate((randmat, solomat), axis=1)
    # possibilite de compresser le code en ne declarant pas de variable solomat

def initialisation (m, n) :
    randmat = np.random.randn(m,n+1)
    return np.concatenate((randmat, np.ones((randmat.shape[0],1))), axis=1)
    # possibilite de compresser le code en ne declarant pas de variable solomat



In [130]:
A = initialisation(2,3)
print(A)
# Note : les colonnes sont converties en float dans le nouveau tableau

[[-1.270485    0.96939671 -1.17312341  1.94362119]
 [-0.41361898 -0.74745481  1.92294203  1.48051479]]
[[1]
 [1]]
[[-1.270485    0.96939671 -1.17312341  1.94362119  1.        ]
 [-0.41361898 -0.74745481  1.92294203  1.48051479  1.        ]]
