- Liste comprehension
- Dictionnaire comprehension
- Traitement de fichier
- Remplissage de string 
- Modules et Packages

# LISTES

In [1]:
villes = ['Paris', 'Berlin', 'Rome', 'Madrid']
villes.append('Dublin')
print(villes)

['Paris', 'Berlin', 'Rome', 'Madrid', 'Dublin']


In [2]:
villes.insert(2, 'Bruxelles')
print(villes)

['Paris', 'Berlin', 'Bruxelles', 'Rome', 'Madrid', 'Dublin']


In [3]:
villes2 = ['Amsterdam', 'Londres']
villes.extend(villes2)
print(villes)

['Paris', 'Berlin', 'Bruxelles', 'Rome', 'Madrid', 'Dublin', 'Amsterdam', 'Londres']


In [4]:
len(villes)

8

In [5]:
villes.sort()
villes

['Amsterdam',
 'Berlin',
 'Bruxelles',
 'Dublin',
 'Londres',
 'Madrid',
 'Paris',
 'Rome']

In [6]:
villes.sort(reverse=True)
villes

['Rome',
 'Paris',
 'Madrid',
 'Londres',
 'Dublin',
 'Bruxelles',
 'Berlin',
 'Amsterdam']

In [7]:
villes.count('Paris')

1

In [8]:
villes.append('Paris')
villes.count('Paris')

2

In [9]:
# villes.clear()

In [10]:
if 'Paris' in villes :
    print('Yes')

Yes


In [11]:
for i in villes :
    print(i)

Rome
Paris
Madrid
Londres
Dublin
Bruxelles
Berlin
Amsterdam
Paris


In [12]:
for i in enumerate(villes) :
    print(i)

(0, 'Rome')
(1, 'Paris')
(2, 'Madrid')
(3, 'Londres')
(4, 'Dublin')
(5, 'Bruxelles')
(6, 'Berlin')
(7, 'Amsterdam')
(8, 'Paris')


In [13]:
liste_2 = [1,2,3,4,5]

# La boucle s'arrete avec la liste la plus courte
for a, b in zip(villes, liste_2) :
    print(a,b)

Rome 1
Paris 2
Madrid 3
Londres 4
Dublin 5


# DICTIONNAIRES

In [14]:
dicoenfr = {
    "chien" : "dog",
    "oiseau" : "bird"
}
inventaire = {
    "poires" : 4300,
    "cerises" : 2400
}

En machine learning, certaines personnes utilisent des dictionnaires pour stocker les parametres de leurs reseaux de neurones

In [15]:
import numpy as np  

parametres = {
    "W1" : np.random.rand(10 , 100),
    "b1" : np.random.rand(10, 1),
    "W2" : np.random.rand(10, 10),
    "b2" : np.random.rand(10, 1)
}

In [16]:
inventaire.values()

dict_values([4300, 2400])

In [17]:
inventaire.keys()

dict_keys(['poires', 'cerises'])

In [18]:
len(inventaire)

2

In [19]:
inventaire["pommes"] = 690
print(inventaire)

{'poires': 4300, 'cerises': 2400, 'pommes': 690}


__Un dictionnaire n'est pas indexe__

In [20]:
# Au lieu de faire des try catch avec des keyerror
print(inventaire.get("peches"))

None


In [21]:
# Pour retourner une valeur par defaut, quand on ne trouve pas :
print(inventaire.get("peches", 0))

0


In [22]:
# Pour rechercher dans un dictionnaire a partir d'une liste de termes : 
inventaire.fromkeys(villes, 'Rien a voir, frerot')

{'Rome': 'Rien a voir, frerot',
 'Paris': 'Rien a voir, frerot',
 'Madrid': 'Rien a voir, frerot',
 'Londres': 'Rien a voir, frerot',
 'Dublin': 'Rien a voir, frerot',
 'Bruxelles': 'Rien a voir, frerot',
 'Berlin': 'Rien a voir, frerot',
 'Amsterdam': 'Rien a voir, frerot'}

In [23]:
nbcerise = inventaire.pop("cerises")
nbcerise

2400

In [24]:
# iterer sur les cles
for i in inventaire : # retourne les cles
    print(i)

# iterer sur les valeurs
for i in inventaire.values() : # retourne les valeurs
    print(i)

# iterer sur les deux
for kle,valeur in inventaire.items() :
    print(kle, valeur)

poires
pommes
4300
690
poires 4300
pommes 690


In [25]:
# Exercice Video 5 
# https://youtu.be/QR-gUWAeLqs

classeur = {
    "positif" : [],
    "negatif" : []
}

def trier(classeur, nombre) :
    if nombre >= 0 :
        classeur["positif"].append(nombre)
    else :
        classeur["negatif"].append(nombre)

trier(classeur=classeur, nombre=2)
trier(classeur=classeur, nombre=4)
trier(classeur=classeur, nombre= -1)
trier(classeur=classeur, nombre=0)
trier(classeur=classeur, nombre=-2)

print(classeur)

{'positif': [2, 4, 0], 'negatif': [-1, -2]}


In [26]:
# LIST COMPREHENSION
# Plus professionnel, en une ligne
# Le processus de creation se fait plus rapidement
liste_carres = [x**2 for x in range(10)]
print(liste_carres)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [27]:
nested_list_comprehension = [[i+j for i in range(3)] for j in range(3)]
print(nested_list_comprehension)

[[0, 1, 2], [1, 2, 3], [2, 3, 4]]


In [28]:
# DICTIONNAIRE COMPREHENSION
# Plus professionnel, en une ligne
# Le processus de creation se fait plus rapidement
dicodor = {
    "0" :"Pierre",
    "1" : "Steve",
    "2" : "Jacques",
    "3" : "Herbert"
}
print(dicodor)

prenoms = ["Pierre", "Steve", "Jacques", "Herbert"]
dico = {key:value for key, value in enumerate(prenoms)}
print(dico)

{'0': 'Pierre', '1': 'Steve', '2': 'Jacques', '3': 'Herbert'}
{0: 'Pierre', 1: 'Steve', 2: 'Jacques', 3: 'Herbert'}


In [29]:
dico.keys()

dict_keys([0, 1, 2, 3])

In [30]:
ages = [25, 30, 45, 67]
dico2 = {prenom:age for prenom, age in zip(prenoms, ages)}
print(dico2)

{'Pierre': 25, 'Steve': 30, 'Jacques': 45, 'Herbert': 67}


In [31]:
dicovieux = {prenom:age for prenom, age in zip(prenoms, ages) if age > 30}
print(dicovieux)

{'Jacques': 45, 'Herbert': 67}


In [32]:
# TUPLE COMPREHENSION
tuple_1 = (i**2 for i in range(10))
print(tuple_1)
# ON VIENT DE CREER UN GENERATEUR

<generator object <genexpr> at 0x7fa2a510edd0>


In [33]:
# POUR CREER UN VERITABLE TUPLE
tuple_1 = tuple((i**2 for i in range(10)))
print(tuple_1)

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)


In [34]:
list_num = [i for i in range(20)]
liste_carres = [x**2 for x in range(20)]
exo_video_5 = {key:value for key, value in zip(list_num, liste_carres)}
print(exo_video_5)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


In [35]:
exo_video_5 = {key:value for key, value in zip([i for i in range(20)], [x**2 for x in range(20)])}
print(exo_video_5)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


In [72]:
# Correction exo_video_5
exo_video_5 = {str(k):k**2 for k in range(0,20)}
print(exo_video_5)

{'0': 0, '1': 1, '2': 4, '3': 9, '4': 16, '5': 25, '6': 36, '7': 49, '8': 64, '9': 81, '10': 100, '11': 121, '12': 144, '13': 169, '14': 196, '15': 225, '16': 256, '17': 289, '18': 324, '19': 361}


__J'ai gagne 0.2 seconde en ecrivant tout sur une seule ligne__

__Son code gagne 0.2 seconde sur le miens. BG !__

# FONCTIONS DE BASE DE PYTHON
[Video 7](https://youtu.be/v7OTVy6whEY)

[Python built-in functions](https://docs.python.org/3/library/functions.html)

## Mathematiques & tris

In [37]:
xv7 = -3
yv7 =-3.2
print("Valeur absolue :", abs(xv7))
print("Arrondi :", round(yv7))


Valeur absolue : 3
Arrondi : -3


In [41]:
liste_1 = [1, 4, -7, 32, 0]
liste_2 = [True, True, False, True]
print("Max d'une liste :", max(liste_1))
print("Min d'une liste :", min(liste_1))
print("Somme d'une liste :", sum(liste_1))
print("LISTE")
# Retourne True quand tous les elements sont True
print("All liste 2 :", all(liste_2))
# Retourne True quand un des elements sont True
print("Any liste 2  :", any(liste_2))
# Retourne True quand tous les elements sont True (False si une valeur est egale a 0)
print("All liste 1 :", all(liste_1))
# Retourne True quand un des elements sont True
print("Any liste 1 :", any(liste_1))

Max d'une liste : 32
Min d'une liste : -7
Somme d'une liste : 30
LISTE
All liste 2 : False
Any liste 2  : True
All liste 1 : False
Any liste 1 : True


In [43]:
print(type(liste_1))
print(tuple(liste_1))

<class 'list'>
(1, 4, -7, 32, 0)


Les fonction list(), tuple() ou dict(), permettent de convertir des elements sequences en d'autres. 

In [45]:
stocks = {
    "pommes" : 23,
    "poires" : 89,
    "scoubidou" : 10
}

fruits_liste = list(stocks.keys())
print(fruits_liste)

['pommes', 'poires', 'scoubidou']


In [46]:
resize = input('Do you want to resize the images ? (yes/no)')
print(resize)

yes


## Strings

In [48]:
x = 25
ville = "Paris"
print("Il fait {} degres a {}".format(x, ville))
print(f"Il fait {x} degres a {ville}")

Il fait 25 degres a Paris
Il fait 25 degres a Paris


In [50]:
parametres = {
    "W1" : np.random.randn(2 , 4),
    "b1" : np.zeros((2, 1)),
    "W2" : np.random.randn(2, 2),
    "b2" : np.zeros((2, 1))
}

# Donne le W1 de la couche 1 & le W2 de la couche 2
for i in range(1, 3) :
    print("couche", i)
    print(parametres["W{}".format(i)])
    print(parametres["W"+str(i)])
    print(parametres[f"W{i}"])

couche 1
[[ 0.07532319  0.19142718  0.26820501  0.44116558]
 [-0.55959943 -0.61946411 -0.02034162  1.69919588]]
[[ 0.07532319  0.19142718  0.26820501  0.44116558]
 [-0.55959943 -0.61946411 -0.02034162  1.69919588]]
[[ 0.07532319  0.19142718  0.26820501  0.44116558]
 [-0.55959943 -0.61946411 -0.02034162  1.69919588]]
couche 2
[[ 0.34519241  0.41862782]
 [-0.95198288  0.26245307]]
[[ 0.34519241  0.41862782]
 [-0.95198288  0.26245307]]
[[ 0.34519241  0.41862782]
 [-0.95198288  0.26245307]]


## Les fichiers

mode a de open, permet de append a la fin.

In [60]:
f = open('fichier.txt', 'w')
f.write("bonjour")
f.write("batard")
f.write("\nbonjour\nbatard")
f.close()

In [61]:
f = open('fichier.txt', 'r')
f.read()

'bonjourbatard\nbonjour\nbatard'

In [62]:
f.close()

In [64]:
with open('fichier.txt', 'r') as f :
    print(f.read())


bonjourbatard
bonjour
batard


In [70]:
with open('fichier.txt', 'a') as f :
    for i in range(10) :
        f.write(f"\n{i}^2 = {str(i**2)}")


In [71]:
# Exercice video 7
with open('fichier.txt', 'r') as f :
    myliste = f.read().split('\n')

print(myliste)

['bonjourbatard', 'bonjour', 'batard0149162536496481', '0', '1', '4', '9', '16', '25', '36', '49', '64', '81', '0 au carre = 0', '1 au carre = 1', '2 au carre = 4', '3 au carre = 9', '4 au carre = 16', '5 au carre = 25', '6 au carre = 36', '7 au carre = 49', '8 au carre = 64', '9 au carre = 81', '0^2 = 0', '1^2 = 1', '2^2 = 4', '3^2 = 9', '4^2 = 16', '5^2 = 25', '6^2 = 36', '7^2 = 49', '8^2 = 64', '9^2 = 81']


In [112]:
# Correction exercice video 7
# #1
print('#1')
with open('fichier.txt', 'r') as f :
    myliste = f.readlines()

print(myliste)

# #2
print('#2')
with open('fichier.txt', 'r') as f :
    myliste = f.read().splitlines()

print(myliste)

# #3
print('#3')
myliste = [line.strip() for line in open('fichier.txt', 'r')] # strip() permet de supprimer les fins de lignes
print(myliste)

['bonjourbatard\n', 'bonjour\n', 'batard0149162536496481\n', '0\n', '1\n', '4\n', '9\n', '16\n', '25\n', '36\n', '49\n', '64\n', '81\n', '0 au carre = 0\n', '1 au carre = 1\n', '2 au carre = 4\n', '3 au carre = 9\n', '4 au carre = 16\n', '5 au carre = 25\n', '6 au carre = 36\n', '7 au carre = 49\n', '8 au carre = 64\n', '9 au carre = 81\n', '0^2 = 0\n', '1^2 = 1\n', '2^2 = 4\n', '3^2 = 9\n', '4^2 = 16\n', '5^2 = 25\n', '6^2 = 36\n', '7^2 = 49\n', '8^2 = 64\n', '9^2 = 81']
['bonjourbatard', 'bonjour', 'batard0149162536496481', '0', '1', '4', '9', '16', '25', '36', '49', '64', '81', '0 au carre = 0', '1 au carre = 1', '2 au carre = 4', '3 au carre = 9', '4 au carre = 16', '5 au carre = 25', '6 au carre = 36', '7 au carre = 49', '8 au carre = 64', '9 au carre = 81', '0^2 = 0', '1^2 = 1', '2^2 = 4', '3^2 = 9', '4^2 = 16', '5^2 = 25', '6^2 = 36', '7^2 = 49', '8^2 = 64', '9^2 = 81']
['bonjourbatard', 'bonjour', 'batard0149162536496481', '0', '1', '4', '9', '16', '25', '36', '49', '64', '81',

__Son conseil de fin, c'est d'arreter de faire ma methode de feignasse, c'est-a-dire d'arreter de taper betement dans Google (ou Qwant) tous les bugs que j'ai, mais plutot de lire les documentations de reference et d'essayer de les comprendre...__

# MODULES ET PACKAGES

[Video 8](https://www.youtube.com/watch?v=mSh4h-J0z1c)

Un module est un fichier python
N.B : Le goto definition peut permettre de retrouver facilement un type (sans avoir a executer type())

Le import from permet d'accelerer le code mais aussi de faire des references aux fonctions, sans appeler la classe au prealable. (import * permettrait la meme chose. Mais le code perdrait en lisibilite)

[Python module index](https://docs.python.org/3/py-modindex.html)

__Package = lot de modules__

## Modules et package de datascience

In [9]:
import math
import random as rd
import statistics as stat
import os
import glob

In [10]:
print(math.cos(math.pi))

-1.0


In [11]:
liste_1 = [1, 5, 32, -9, 0]
print(stat.mean(liste_1))
print(stat.variance(liste_1))
# Standard deviation = ecart type

5.8
240.7


In [13]:
print(rd.choice(liste_1))
print(rd.choice(['jean', 'anne', 'mohamed']))

1
anne


In [52]:
# Permet d'orienter le resultat de la fonction random
#rd.seed(0) # Permet de figer le resultat du random
print(rd.choice(['jean', 'anne', 'mohamed']))

mohamed


In [53]:
print(rd.randint(0,20))
print(rd.random())
print(rd.randrange(0,10,2))

1
0.3012676595157123
0


In [76]:
# lancer de des
print(rd.randrange(1,7))
# lancer de des
print(rd.randint(1,6))

3
4


In [58]:
# retourne un echantillon de k element parmis une population donnee 
print(rd.sample(population=['michel', 'jacquie', 'fatima', 'rachid', 'enzo','hans'], k=2))

['rachid', 'enzo']


In [65]:
# dix nombre aleatoires entre 0 et 100
rd.sample(population=range(100), k=10)

[76, 68, 4, 25, 52, 37, 78, 33, 19, 88]

In [67]:
# dix nombre aleatoires entre 0 et 100
rd.sample(population=range(100), k=rd.randrange(10))

[40, 46, 17, 48, 58]

In [80]:
rd.shuffle(liste_1)
print(liste_1)

[32, 0, 1, -9, 5]


## Fichiers

In [81]:
# donne l'adresse du repertoire courant (current working directory)
print(os.getcwd())

/home/maximorose/Github_repositories/machinelearnia


In [91]:
# la fonction glob.glob retourne tous les noms des fichiers que l'on a
print(glob.glob('*.py'))
print(glob.glob('ml_*'))

['ml_python.py']
['ml_python.py', 'ml_jupyter.ipynb']


In [111]:
py_files = glob.glob('*.py')
print(py_files)
pytxt_files = py_files + (glob.glob('*.txt'))
print(pytxt_files)
# None type volontaire de glob
pytxt_files += (glob.glob('*.JPG'))
print(pytxt_files)
# => sans impact sur la liste

['ml_python.py']
['ml_python.py', 'fichier.txt', 'fruits.txt']
['ml_python.py', 'fichier.txt', 'fruits.txt']


In [90]:
print(glob.glob('*'))

['ml_python.py', 'ml_jupyter.ipynb', 'fichier.txt', 'assets', 'README.md']


Creation d'un dictionnaire dont les cles sont les noms des fichiers et les valeurs associees, la liste de leurs lignes

In [118]:
filenames = glob.glob('*.txt')
# Rappel exo precedent
# myliste = [line.strip() for line in open('fichier.txt', 'r')] # strip() permet de supprimer les fins de lignes
filecontents = [[line.strip() for line in open(file, 'r')] for file in filenames]
# for file in filenames :
#     with open(file, 'r') as f :
#         # output_texts += f.read() + " "
#         filecontent.append(f.read())
output_texts = {filename : content for filename, content in zip(filenames, filecontents)}

# Affiche le contenu d'un des fichiers au hasard, sur la base du dictionnaires qui a chaque nom de fichier associe un contenu
print(output_texts[filenames[rd.randrange(0,len(filenames))]])

# output_texts    

['pommes', 'poires', 'abrictos']


In [ ]:
# correction
filenames = glob.glob('*.txt')
d = {}
for file in filenames :
    with open(file, 'r') as f :
        d[file] = f.read().splitlines()